Take this array to perform your actions upon (input this code) → input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])

1. Mean removal (so that each feature is centered on zero)
2. Scale the data
3. Normalize the data
4. Binarize the data

In [19]:
import numpy as np
from sklearn import preprocessing

In [15]:
sns.set_style('darkgrid')

In [2]:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])

In [3]:
input_data

array([[ 3. , -1.5,  3. , -6.4],
       [ 0. ,  3. , -1.3,  4.1],
       [ 1. ,  2.3, -2.9, -4.3]])

## 1. Mean Removal

In [7]:
print("Mean: ", input_data.mean(axis=0))
print("Standard Deviation: ", input_data.std(axis=0))

Mean:  [ 1.33333333  1.26666667 -0.4        -2.2       ]
Standard Deviation:  [1.24721913 1.97709102 2.49131826 4.53651849]


In [20]:
input_data_standarized = preprocessing.scale(input_data)
print("Mean and Satndard Deviation After Mean Removal\n", "*" * 50)
print("Mean: ", input_data_standarized.mean(axis=0))
print("Standard Deviation: ", input_data_standarized.std(axis=0))

Mean and Satndard Deviation After Mean Removal
 **************************************************
Mean:  [ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
Standard Deviation:  [1. 1. 1. 1.]


As we can see that mean is nearly zero for each feature and stadard deviation is 1

## 2. Scaling

We will scale the data in the range of 0 and 1

In [24]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
input_data_scaled = data_scaler.fit_transform(input_data)
print("Scaled Data\n", input_data_scaled)

Scaled Data
 [[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


## 3. Normalization

In [25]:
input_data_normalized = preprocessing.normalize(input_data, norm='l1', axis=0)
print("Normalized Data:\n", input_data_normalized)

Normalized Data:
 [[ 0.75       -0.22058824  0.41666667 -0.43243243]
 [ 0.          0.44117647 -0.18055556  0.27702703]
 [ 0.25        0.33823529 -0.40277778 -0.29054054]]


# 4. Binarization

In binarization we need to set a threshold. Values greater that threshold maps to 1, while values less than or equal to the threshold maps to  zero. Here we are setting threshold as 1.5

In [26]:
input_data_binarized = preprocessing.Binarizer(threshold=1.5).transform(input_data)
print("Binarized Data:\n", input_data_binarized)

Binarized Data:
 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]
